my_file = open('text_111.txt', "r")
content = my_file.read()
print(f'содержимое файла: \n{content}')
my_file = open('text_111.txt', "r")
content = my_file.readlines()
print(f'кол-во строк в файле : {len(content)}')
my_file = open('text_111.txt', 'r')
content = my_file.read()
content = content.split()
print(f'Общее количество слов - {len(content)}')
my_file.close()